version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: openmetadata_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: openmetadata_db
      MYSQL_USER: openmetadata_user
      MYSQL_PASSWORD: openmetadata_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "openmetadata_user", "-popenmetadata_password"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - shared-net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: openmetadata_elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    networks:
      - shared-net

  openmetadata:
    image: openmetadata/server:latest
    container_name: openmetadata
    ports:
      - "8585:8585"  # UI
      - "9292:9200"  # Optional: Search
    environment:
      SERVER_HOST_API_URL: "http://openmetadata:8585/api"
      OPENMETADATA_DATABASE_HOST: mysql
      OPENMETADATA_DATABASE_PORT: 3306
      OPENMETADATA_DATABASE_USER: openmetadata_user
      OPENMETADATA_DATABASE_PASSWORD: openmetadata_pass
      OPENMETADATA_DATABASE_NAME: openmetadata_db
      OPENMETADATA_DATABASE_SCHEME: mysql
      ELASTICSEARCH_HOST: elasticsearch
      ELASTICSEARCH_PORT: 9200
    depends_on:
      mysql:  # Thay 'mysql' bằng container_name
        condition: service_healthy
      elasticsearch:  # Thay 'elasticsearch' bằng container_name
        condition: service_started
    networks:
      - shared-net



  #######################
  # 1. Apache NiFi
  #######################
  nifi:
    image: apache/nifi:1.25.0
    container_name: nifi
    ports:
      - "8083:8083"
      - "8081:8081"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - NIFI_WEB_HTTP_PORT=8081
    volumes:
      - nifi_conf:/opt/nifi/nifi-current/conf
      - nifi_logs:/opt/nifi/nifi-current/logs
      - nifi_repo:/opt/nifi/nifi-current/database_repository
      - nifi_flow:/opt/nifi/nifi-current/flowfile_repository
      - nifi_content:/opt/nifi/nifi-current/content_repository
      - nifi_provenance:/opt/nifi/nifi-current/provenance_repository
      - nifi_python_ext:/opt/nifi/nifi-current/python_extensions
      - nifi_nar_ext:/opt/nifi/nifi-current/nar_extensions
      - nifi_state:/opt/nifi/nifi-current/state
      - /home/qlcladmin/private-datalake/fastapi_app/uploaded_files:/data/uploaded_files
      - /home/qlcladmin/private-datalake/venv:/venv
      - /home/qlcladmin/private-datalake/scripts:/scripts
      - /home/qlcladmin/private-datalake/fastapi_app/tmp_files:/data/tmp_files
      - /home/qlcladmin/miniconda3:/conda
      - /home/qlcladmin/private-datalake/data/tmp:/data/tmp  
      - /home/qlcladmin/private-datalake/python-venv:/opt/nifi/nifi-current/python-venv
      # - ./conf/nifi.properties:/opt/nifi/nifi-current/conf/nifi-orig.properties
      
    networks:
      - shared-net

  #######################
  # 2. MinIO
  #######################
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    command: server /data --console-address ":9001"
    volumes:
      - ./minio_data:/data
    networks:
      - shared-net

  #######################
  # 3. Apache Spark
  #######################
  spark:
    image: bitnami/spark:3.5
    container_name: spark
    environment:
      - SPARK_MODE=master
    ports:
      - "8082:8080"
    networks:
      - shared-net

  #######################
  # 4. Neo4j
  #######################
  neo4j:
    image: neo4j:5
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/phongthang2012
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_PLUGINS=["graph-data-science"]
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/var/lib/neo4j/import
      - ./neo4j/plugins:/plugins
    networks:
      - shared-net

  #######################
  # 5. PostgreSQL
  #######################
  # postgres:
  #   image: postgres:15
  #   container_name: postgres
  #   restart: always
  #   environment:
  #     POSTGRES_USER: admin
  #     POSTGRES_PASSWORD: admin123
  #     POSTGRES_DB: datalake
  #   volumes:
  #     - ./postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - shared-net

  #######################
  # 6. FastAPI
  #######################
  fastapi:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.10
    container_name: fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi_app:/app
    environment:
      - MODULE_NAME=app
    networks:
      - shared-net
    command: bash -c "pip install -r /app/requirements.txt && uvicorn app:app --host 0.0.0.0 --port 8000"

  #######################
  # 7. MongoDB
  #######################
  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
    restart: always
    networks:
      - shared-net
  #######################
  # 8. Qdrant
  #######################
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_data:/qdrant/storage
    networks:
      - shared-net

volumes:
  nifi_conf:
  nifi_logs:
  nifi_repo:
  nifi_flow:
  nifi_content:
  nifi_provenance:
  nifi_python_ext:
  nifi_nar_ext:
  nifi_state:
  mongo_data:
  mysql_data:

networks:
  shared-net:
