version: '3.1'

services:
  web:
    image: odoo:17
    depends_on:
      - db
    ports:
      - 8069:8069
    volumes:
      - ./odoo_data:/var/lib/odoo

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - ./db_data:/var/lib/postgresql/data
